spring:
  application:
    name: "exchange-spring"
  datasource:
    url: jdbc:h2:mem:dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
  webflux:
    problemdetails:
      enabled: true
  config:
    import: "optional:configserver:"
  cloud:
    function:
      definition: transactionMessage
    stream:
      bindings:
        transactionMessage-out-0:
          destination: transaction-message
        transactionMessage-in-0:
          destination: transaction-message
          group: ${spring.application.name}

  rabbitmq:
    host: rabbitmq-dc-server
    port: 5672
    username: admin
    password: admin
    connection-timeout: 10s

  data:
    redis:
      host: redis-dc-server
      port: 6379
      client:
        config:
          tcpKeepAlive: true

server:
  port: 80

jwt:
  secretKey: iEQlMJR858sWj1MLeIKB115gdL50dshhdMioXKl3oOnQ21HRTzurrW3rjpmdiTgg